version: '2'
services:
  db:
    image: postgres:14
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo15@2021      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo15:
    image: odoo:15
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
      - "8080:8080"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo15@2021
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
  #code-server:
  #  image: codercom/code-server:latest
  #  ports:
  #    - "8081:8080"  # Sesuaikan port Code-Server sesuai kebutuhan
  #  volumes:
      #- ./code:/home/coder/project  # Mount volume untuk menyimpan proyek kode 
  #    - ./code:/mnt/extra-addons 


#docker push ninofelinosystem/mypc:tagname      

    

 